# Generated by Django 5.0.3 on 2024-03-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='exit', max_length=1000, verbose_name='محتوى المنشور'),
            preserve_default=False,
        ),
    ]
