# Generated by Django 5.0.3 on 2024-04-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_comment_auther_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post', verbose_name='الصورة'),
        ),
    ]
