# Generated by Django 5.0.3 on 2024-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='p_type',
            field=models.CharField(choices=[('question', 'Question'), ('post', 'Post'), ('article', 'Article')], max_length=500, verbose_name='Post Type'),
        ),
    ]
